### ISSUE TITLE
404 error when trying to install

### ISSUE THREAD

**Issue by Had01** [Hillshum/OctoPrint-CostEstimation#6]
Hello,
I am getting error:

ERROR: HTTP error 404 while getting https://github.com/OllisGit/OctoPrint-CostEstimation/releases/download/v3.5.2/master.zip
ERROR: Could not install requirement https://github.com/OllisGit/OctoPrint-CostEstimation/releases/download/v3.5.2/master.zip because of HTTP error 404 Client Error: Not Found for url: https://github.com/OllisGit/OctoPrint-CostEstimation/releases/download/v3.5.2/master.zip for URL https://github.com/OllisGit/OctoPrint-CostEstimation/releases/download/v3.5.2/master.zip

Please update access to repo. Thanks.

**Comment by Had01** [comment]
Sorry, bad URL

**Comment by DanielEXQ** [comment]
Hi,
i get the same error. The Path https://github.com/OllisGit/OctoPrint-CostEstimation/releases/download/3.5.2/master.zip response 404 - not found.

`/home/pi/oprint/bin/python -m pip --disable-pip-version-check install https://github.com/OllisGit/OctoPrint-CostEstimation/releases/download/3.5.2/master.zip --no-cache-dir
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting https://github.com/OllisGit/OctoPrint-CostEstimation/releases/download/3.5.2/master.zip
ERROR: HTTP error 404 while getting https://github.com/OllisGit/OctoPrint-CostEstimation/releases/download/3.5.2/master.zip
ERROR: Could not install requirement https://github.com/OllisGit/OctoPrint-CostEstimation/releases/download/3.5.2/master.zip because of HTTP error 404 Client Error: Not Found for url: https://github.com/OllisGit/OctoPrint-CostEstimation/releases/download/3.5.2/master.zip for URL https://github.com/OllisGit/OctoPrint-CostEstimation/releases/download/3.5.2/master.zip`

**Comment by Had01** [comment]
You need to use: **https://github.com/Hillshum/OctoPrint-CostEstimation/releases/latest/download/master.zip** and insert it to plugin manager manually to install
